### ISSUE TITLE
An Event Emitter Example

### ISSUE THREAD

**Issue by fatihayyildiz** [valdio/ReactNative_Kotlin_Bridge#1]
Thanks for good example and article @valdio 

I have a question. I already implement Kotlin module in my React native project. But my need is this:

I have a activity which is written in Kotlin and I am opening it in my RN Project. I want to fire an event from this Kotlin page throught to JS side. I did same part in my MainApplication.java  file. I created EventEmitter module also and I can trigger it. But from Kotlin Activity, I dont have an ReactApplicationContext in Kotlin Activity. Could you please give an idea about, how can I trigger event to JS from Kotlin Activity ? I am not good at Kotlin and I search couple days for event emitter topic but I always find an open Activity example. 

Thanks for your time

**Comment by valdio** [comment]
Hi @fatihayyildiz 

Your requirements seem too specific and I cannot think of any solution with the provided information. maybe you can give me a demo of what you are trying to build! 

Closing this issue because is not related to the example. You can continue to add comments in this thread.
